set -euo pipefail

function profile_filename() {
    if [[ -f ~/.profile ]]
    then
        echo ~/.profile
    elif [[ -f ~/.bash_profile ]]
    then
        echo ~/.bash_profile
    fi
}

# Delete and remake install directory
rm -Rf ~/.mhb-util
SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
cp -r "$SCRIPT_DIR" ~/.mhb-util


# Add path
PROFILE_FILENAME=$(profile_filename)
if ! grep -Fxq "# Generated by MHB utilities" "$PROFILE_FILENAME"
then
    echo '#
# Generated by MHB utilities
#
export PATH=$PATH:~/.mhb-util
#
# End of generated block
#' >> "$PROFILE_FILENAME"
fi

