set -euo pipefail

function profile_filename() {
    if [[ -f ~/.profile ]]
    then
        echo ~/.profile
    elif [[ -f ~/.bash_profile ]]
    then
        echo ~/.bash_profile
    fi
}

(
    cd manager-app/
    cargo build --release
)

# Delete and remake install directory
rm -Rf ~/.mhb-util
mkdir ~/.mhb-util
mkdir ~/.mhb-util/apps
cp manager-app/target/release/manager-app ~/.mhb-util
cp config.json ~/.mhb-util
cp manager-app/test/echo.bash ~/.mhb-util

# Add path
PROFILE_FILENAME=$(profile_filename)
if ! grep -Fxq "# Generated by MHB utilities" "$PROFILE_FILENAME"
then
    echo '#
# Generated by MHB utilities
#
export PATH=$PATH:~/.mhb-util
#
# End of generated block
#' >> "$PROFILE_FILENAME"
fi

